[package]
name = "turbo_atlas_icons"
version = "0.1.0"
edition = "2021"

[dependencies]
 bevy = { version = "0.13.2" , features = [ "jpeg", "tga", "serialize"  ] }
 bevy_asset_loader = { version = "0.20.1", features = ["progress_tracking","2d","standard_dynamic_assets"] }

 
 # sickle_ui = { git = "https://github.com/UmbraLuminosa/sickle_ui" }

